
import java.text.MessageFormat;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author akshay pandhare
 */
public class JavaPOS extends javax.swing.JFrame {

    private DefaultTableModel DefaultTableModel;

    /**
     * Creates new form JavaPOS
     */
    public JavaPOS() {
        initComponents();
    }
       
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
//=======================================Function=============================================
    
    public void ItemCost()
    {
      double sum = 0;
      
      for(int i = 0; i < jTable1.getRowCount();i++)
      {
          sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
      }
      jtxtSubtotal.setText(Double.toString(sum));
      double cTotal1 = Double.parseDouble(jtxtSubtotal.getText());
      
      double cTax =  (cTotal1 * 3.9)/100;
      String iTaxTotal = String.format("₹ %.2f", cTax);
      jtxtTax.setText(iTaxTotal);
      
      String iSubtotal = String.format("₹ %.2f", cTotal1);
      jtxtSubtotal.setText(iSubtotal);
     
       String iTotal = String.format("₹ %.2f", cTotal1 + cTax);
      jtxtTotal.setText(iTotal);
      
       String BarCode = String.format("Total is %.2f", cTotal1 + cTax);
      jtxtBarCode.setText(BarCode);
    }
    
//=============================================Function Change========================================================

     public void Change()
     {
         double sum = 0;
         double tax = 3.9;
         double Cash = Double.parseDouble(jtxtDisplay.getText());
         
         for(int i = 0; i < jTable1.getRowCount();i++)
      {
          sum = sum + Double.parseDouble(jTable1.getValueAt(i, 2).toString());
      }
         double cTax = (sum * 3.9 )/100;
         double cChange = (Cash - (sum + cTax));
         
         String ChangeGiven = String.format("₹ %.2f", cChange);
         jtxtChange.setText(ChangeGiven);
     }
    
    
    
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        JbtnBurger = new javax.swing.JButton();
        JbtnNuddles = new javax.swing.JButton();
        JbtnCappeccino = new javax.swing.JButton();
        JbtnBlackTea = new javax.swing.JButton();
        JbtnBiryani = new javax.swing.JButton();
        JbtnDumBiryani = new javax.swing.JButton();
        JbtnCokokola = new javax.swing.JButton();
        JbtnCoffee = new javax.swing.JButton();
        jbtnBreadRoll = new javax.swing.JButton();
        JbtnPizza = new javax.swing.JButton();
        JbtnMaggie = new javax.swing.JButton();
        JbtnKantkiChicken = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel2 = new javax.swing.JPanel();
        Jbtn9 = new javax.swing.JButton();
        Jbtn7 = new javax.swing.JButton();
        Jbtn8 = new javax.swing.JButton();
        Jbtn4 = new javax.swing.JButton();
        Jbtn5 = new javax.swing.JButton();
        Jbtn6 = new javax.swing.JButton();
        Jbtn1 = new javax.swing.JButton();
        Jbtn2 = new javax.swing.JButton();
        Jbtn3 = new javax.swing.JButton();
        Jbtn0 = new javax.swing.JButton();
        JbtnDot = new javax.swing.JButton();
        JbtnC = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jtxtTotal = new javax.swing.JTextField();
        jtxtSubtotal = new javax.swing.JTextField();
        jtxtTax = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jtxtChange = new javax.swing.JTextField();
        jtxtDisplay = new javax.swing.JTextField();
        JcboPayment = new javax.swing.JComboBox<>();
        jPanel7 = new javax.swing.JPanel();
        JbtnExit = new javax.swing.JButton();
        JbtnPay = new javax.swing.JButton();
        JbtnReset = new javax.swing.JButton();
        JbtnRemove = new javax.swing.JButton();
        JbtnPrint = new javax.swing.JButton();
        jtxtBarCode = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbtnBurger.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnBurger.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (6).jpg"))); // NOI18N
        JbtnBurger.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBurgerActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnBurger, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 20, 140, 140));

        JbtnNuddles.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnNuddles.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/360_F_202368757_hMVz6S8RmDdPM1wm8YW7uC0FefyDaWr7.jpg"))); // NOI18N
        JbtnNuddles.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnNuddlesActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnNuddles, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 140, 140));

        JbtnCappeccino.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnCappeccino.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/Coffees.jpg"))); // NOI18N
        JbtnCappeccino.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCappeccinoActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnCappeccino, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 20, 140, 140));

        JbtnBlackTea.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnBlackTea.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (3).jpg"))); // NOI18N
        JbtnBlackTea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBlackTeaActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnBlackTea, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 20, 140, 140));

        JbtnBiryani.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnBiryani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (10).jpg"))); // NOI18N
        JbtnBiryani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnBiryaniActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnBiryani, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 170, 140, 140));

        JbtnDumBiryani.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnDumBiryani.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (12).jpg"))); // NOI18N
        JbtnDumBiryani.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDumBiryaniActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnDumBiryani, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 170, 140, 140));

        JbtnCokokola.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnCokokola.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (9).jpg"))); // NOI18N
        JbtnCokokola.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCokokolaActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnCokokola, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 170, 140, 140));

        JbtnCoffee.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnCoffee.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (4).jpg"))); // NOI18N
        JbtnCoffee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCoffeeActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnCoffee, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 170, 140, 140));

        jbtnBreadRoll.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jbtnBreadRoll.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (8).jpg"))); // NOI18N
        jbtnBreadRoll.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbtnBreadRollActionPerformed(evt);
            }
        });
        jPanel1.add(jbtnBreadRoll, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 320, 140, 140));

        JbtnPizza.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnPizza.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (2).jpg"))); // NOI18N
        JbtnPizza.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPizzaActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnPizza, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 320, 140, 140));

        JbtnMaggie.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnMaggie.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (7).jpg"))); // NOI18N
        JbtnMaggie.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnMaggieActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnMaggie, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 140, 140));

        JbtnKantkiChicken.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnKantkiChicken.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Image/images (11).jpg"))); // NOI18N
        JbtnKantkiChicken.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnKantkiChickenActionPerformed(evt);
            }
        });
        jPanel1.add(JbtnKantkiChicken, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 320, 140, 140));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(690, 10, 630, 490));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Item", "Qty", "Amount"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 300, -1));

        jPanel2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        Jbtn9.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn9.setText("9");
        Jbtn9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn9ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn9, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 20, 100, 100));

        Jbtn7.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn7.setText("7");
        Jbtn7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn7ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 20, 100, 100));

        Jbtn8.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn8.setText("8");
        Jbtn8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn8ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn8, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 20, 100, 100));

        Jbtn4.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn4.setText("4");
        Jbtn4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn4ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 100, 100));

        Jbtn5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn5.setText("5");
        Jbtn5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn5ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn5, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 130, 100, 100));

        Jbtn6.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn6.setText("6");
        Jbtn6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn6ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn6, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 130, 100, 100));

        Jbtn1.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn1.setText("1");
        Jbtn1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn1ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, 100, 100));

        Jbtn2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn2.setText("2");
        Jbtn2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn2ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 240, 100, 100));

        Jbtn3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn3.setText("3");
        Jbtn3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn3ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn3, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 240, 100, 100));

        Jbtn0.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        Jbtn0.setText("0");
        Jbtn0.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Jbtn0ActionPerformed(evt);
            }
        });
        jPanel2.add(Jbtn0, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 100, 100));

        JbtnDot.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnDot.setText(".");
        JbtnDot.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnDotActionPerformed(evt);
            }
        });
        jPanel2.add(JbtnDot, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 350, 100, 100));

        JbtnC.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnC.setText("C");
        JbtnC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnCActionPerformed(evt);
            }
        });
        jPanel2.add(JbtnC, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 350, 100, 100));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 350, 490));

        jPanel3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel4.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel4.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel3.add(jPanel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1340, 180));

        jPanel5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Total");
        jPanel5.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setText("Tax");
        jPanel5.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 40));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel3.setText("Sub Total");
        jPanel5.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 130, 40));

        jtxtTotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel5.add(jtxtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 130, 190, 40));

        jtxtSubtotal.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel5.add(jtxtSubtotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 10, 190, 40));

        jtxtTax.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel5.add(jtxtTax, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 70, 190, 40));

        jPanel3.add(jPanel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 20, 380, 180));

        jPanel6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel6.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel4.setText("Payment Method");
        jPanel6.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 200, 40));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setText("Cash");
        jPanel6.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 130, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel6.setText("Change");
        jPanel6.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 130, 130, 40));

        jtxtChange.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel6.add(jtxtChange, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 130, 190, 40));

        jtxtDisplay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jPanel6.add(jtxtDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 80, 190, 40));

        JcboPayment.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JcboPayment.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cash", "Visa Card", "Master Card" }));
        jPanel6.add(JcboPayment, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 140, 40));

        jPanel3.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 20, 380, 180));

        jPanel7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.LOWERED));
        jPanel7.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        JbtnExit.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        JbtnExit.setText("Exit");
        JbtnExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnExitActionPerformed(evt);
            }
        });
        jPanel7.add(JbtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 380, 50));

        JbtnPay.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnPay.setText("Pay");
        JbtnPay.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPayActionPerformed(evt);
            }
        });
        jPanel7.add(JbtnPay, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 120, 50));

        JbtnReset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnReset.setText("Reset");
        JbtnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnResetActionPerformed(evt);
            }
        });
        jPanel7.add(JbtnReset, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 10, 120, 50));

        JbtnRemove.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnRemove.setText("Remove");
        JbtnRemove.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnRemoveActionPerformed(evt);
            }
        });
        jPanel7.add(JbtnRemove, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 70, 120, 50));

        JbtnPrint.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        JbtnPrint.setText("Print");
        JbtnPrint.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                JbtnPrintActionPerformed(evt);
            }
        });
        jPanel7.add(JbtnPrint, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 70, 120, 50));

        jPanel3.add(jPanel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(890, 20, 420, 190));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 520, 1340, 220));

        jtxtBarCode.setFont(new java.awt.Font("C39HrP24DhTt", 0, 48)); // NOI18N
        jtxtBarCode.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxtBarCodeActionPerformed(evt);
            }
        });
        getContentPane().add(jtxtBarCode, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 440, 300, 70));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Jbtn7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn7ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn7.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn7.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn7ActionPerformed

    private void Jbtn8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn8ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn8.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn8.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn8ActionPerformed

    private void Jbtn9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn9ActionPerformed
       
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn9.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn9.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn9ActionPerformed

    private void Jbtn4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn4ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn4.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn4.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn4ActionPerformed

    private void Jbtn5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn5ActionPerformed
       String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn5.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn5.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn5ActionPerformed

    private void Jbtn6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn6ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn6.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn6.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn6ActionPerformed

    private void Jbtn1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn1ActionPerformed
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn1.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn1.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn1ActionPerformed

    private void Jbtn2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn2ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn2.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn2.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn2ActionPerformed

    private void Jbtn3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn3ActionPerformed
       
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn3.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn3.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn3ActionPerformed

    private void Jbtn0ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Jbtn0ActionPerformed
        
        String Enternumber = jtxtDisplay.getText();
        
        if(Enternumber == "")
        {
            jtxtDisplay.setText(Jbtn0.getText());
        }
        else
        {
            Enternumber = jtxtDisplay.getText() + Jbtn0.getText();
            jtxtDisplay.setText(Enternumber);
        }
    }//GEN-LAST:event_Jbtn0ActionPerformed

    private void JbtnDotActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDotActionPerformed
        
        if(! jtxtDisplay.getText().contains("."))
        {
             jtxtDisplay.setText(jtxtDisplay.getText() + JbtnDot.getText());
        }
    }//GEN-LAST:event_JbtnDotActionPerformed

    private void JbtnCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCActionPerformed
        jtxtDisplay.setText("");
        jtxtChange.setText("");
        
    }//GEN-LAST:event_JbtnCActionPerformed

    private void JbtnPayActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPayActionPerformed
        
        if(JcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
                }
    }//GEN-LAST:event_JbtnPayActionPerformed

    private void jbtnBreadRollActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbtnBreadRollActionPerformed
        
        int PriceOfItem = 25;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Bread Roll", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_jbtnBreadRollActionPerformed

    private void jtxtBarCodeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxtBarCodeActionPerformed
      
    }//GEN-LAST:event_jtxtBarCodeActionPerformed

    private void JbtnPizzaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPizzaActionPerformed
          int PriceOfItem = 250;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Pizza", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnPizzaActionPerformed

    private void JbtnMaggieActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnMaggieActionPerformed
        
          int PriceOfItem = 175;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Maggie", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnMaggieActionPerformed

    private void JbtnKantkiChickenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnKantkiChickenActionPerformed
      
         int PriceOfItem = 80;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"KantkiChicken", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnKantkiChickenActionPerformed

    private void JbtnBiryaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBiryaniActionPerformed
       
        int PriceOfItem = 130;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Biryani", "1",PriceOfItem});
        ItemCost();
        
    }//GEN-LAST:event_JbtnBiryaniActionPerformed

    private void JbtnDumBiryaniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnDumBiryaniActionPerformed
        
         int PriceOfItem = 150;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"DumBiryani", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnDumBiryaniActionPerformed

    private void JbtnCokokolaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCokokolaActionPerformed
        
         int PriceOfItem = 45;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coko Kola", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnCokokolaActionPerformed

    private void JbtnCoffeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCoffeeActionPerformed
         
        int PriceOfItem = 45;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Coffee", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnCoffeeActionPerformed

    private void JbtnNuddlesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnNuddlesActionPerformed
       
         int PriceOfItem = 125;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Nuddles", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnNuddlesActionPerformed

    private void JbtnCappeccinoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnCappeccinoActionPerformed
        
        int PriceOfItem = 40;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Cappeccino", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnCappeccinoActionPerformed

    private void JbtnBlackTeaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBlackTeaActionPerformed
        
        int PriceOfItem = 45;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Black Tea", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnBlackTeaActionPerformed

    private void JbtnBurgerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnBurgerActionPerformed
        
        int PriceOfItem = 150;
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.addRow(new Object[]{"Burger", "1",PriceOfItem});
        ItemCost();
    }//GEN-LAST:event_JbtnBurgerActionPerformed

    private void JbtnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnResetActionPerformed
      DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0);
        jtxtChange.setText("");
        jtxtTax.setText("");
        jtxtTotal.setText("");
        jtxtSubtotal.setText("");
        jtxtDisplay.setText("");
        jtxtBarCode.setText("");
    }//GEN-LAST:event_JbtnResetActionPerformed

    private void JbtnPrintActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnPrintActionPerformed
        
       MessageFormat header = new MessageFormat("Printing in Progress");
       MessageFormat footer = new MessageFormat("Page {0,number,integer}");
       
       try
       {
           jTable1.print(JTable.PrintMode.NORMAL,header,footer);
       }
       catch(java.awt.print.PrinterException e)
       {
           System.err.format("No printer found", e.getMessage());
       }
    }//GEN-LAST:event_JbtnPrintActionPerformed

    private void JbtnRemoveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnRemoveActionPerformed
        
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        
        int RemoveItem = jTable1.getSelectedRow();
        if(RemoveItem >= 0)
        {
            model.removeRow(RemoveItem);
        }
        ItemCost();
        
        if(JcboPayment.getSelectedItem().equals("Cash"))
        {
            Change();
        }
        else
        {
                jtxtChange.setText("");
                jtxtDisplay.setText("");
                }
        
    }//GEN-LAST:event_JbtnRemoveActionPerformed
private JFrame frame;
    private void JbtnExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_JbtnExitActionPerformed
       
        frame = new JFrame("Exit");
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to Exit","Point of Sale",
             JOptionPane.YES_NO_OPTION) == JOptionPane.YES_NO_OPTION)
        {
            System.exit(0);
        }
    }//GEN-LAST:event_JbtnExitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JavaPOS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JavaPOS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Jbtn0;
    private javax.swing.JButton Jbtn1;
    private javax.swing.JButton Jbtn2;
    private javax.swing.JButton Jbtn3;
    private javax.swing.JButton Jbtn4;
    private javax.swing.JButton Jbtn5;
    private javax.swing.JButton Jbtn6;
    private javax.swing.JButton Jbtn7;
    private javax.swing.JButton Jbtn8;
    private javax.swing.JButton Jbtn9;
    private javax.swing.JButton JbtnBiryani;
    private javax.swing.JButton JbtnBlackTea;
    private javax.swing.JButton JbtnBurger;
    private javax.swing.JButton JbtnC;
    private javax.swing.JButton JbtnCappeccino;
    private javax.swing.JButton JbtnCoffee;
    private javax.swing.JButton JbtnCokokola;
    private javax.swing.JButton JbtnDot;
    private javax.swing.JButton JbtnDumBiryani;
    private javax.swing.JButton JbtnExit;
    private javax.swing.JButton JbtnKantkiChicken;
    private javax.swing.JButton JbtnMaggie;
    private javax.swing.JButton JbtnNuddles;
    private javax.swing.JButton JbtnPay;
    private javax.swing.JButton JbtnPizza;
    private javax.swing.JButton JbtnPrint;
    private javax.swing.JButton JbtnRemove;
    private javax.swing.JButton JbtnReset;
    private javax.swing.JComboBox<String> JcboPayment;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JButton jbtnBreadRoll;
    private javax.swing.JTextField jtxtBarCode;
    private javax.swing.JTextField jtxtChange;
    private javax.swing.JTextField jtxtDisplay;
    private javax.swing.JTextField jtxtSubtotal;
    private javax.swing.JTextField jtxtTax;
    private javax.swing.JTextField jtxtTotal;
    // End of variables declaration//GEN-END:variables
}
